---
# tasks file for deploy

- name: create temporary deploy directory
  tempfile:
    state: directory
    suffix: trapper
  register: tempdir

- name: template trapper components
  template:
    src: "{{ item }}.j2"
    dest: "{{ tempdir.path }}/{{ item }}"
  changed_when: no
  with_items:
  - "{{ trapper_deployments_files }}"

#ToDo: Move to k8s_raw after ansible 2.5+
- name: Create a trapper objects by reading the definition from a file
  shell: oc create -f {{ item }} -n {{ trapper_namespace }}
  with_items:
  - "{{ tempdir.path }}/trapper-deployment.yaml"
  - "{{ tempdir.path }}/trapper-svc.yaml"
  ignore_errors: true

- name: Create a trapper debugger objects by reading the definition from a file
  shell: oc create -f {{ item }} -n {{ trapper_namespace }}
  with_items:
  - "{{ tempdir.path }}/trapper-debugger-deployment.yaml"
  - "{{ tempdir.path }}/trapper-debugger-svc.yaml"
  when: trapper_deploy_debugger
  ignore_errors: true

- name: Delete temp directory
  file:
    name: "{{ tempdir.path }}"
    state: absent
  changed_when: False
  check_mode: no